id: PB0D99A09
initial_creation_type: input
source_metadata:
  title: Könchok Tenpe Drönme Series
  language: en
  description: 'Texts by the celebrated scholar Könchok Tenpe Drönme (dkon mchog bstan
    pa''i sgron me, 1762–1823), who was the Third Gungthang incarnation and the 21st
    throne-holder of Labrang Tashikhyil:'
  volume:
    02ba9a10d48a44aca9b0517a5f9183bc:
      title: Verses of Advice for Meditating on Impermanence
      parent: Advice
    a4fcd8009cbc426988b742a9978f51f5:
      title: 'Words of Truth: An Aspiration for the Spread of the Noble Gendenpa Tradition'
      parent: Aspiration Prayers
    f83818c4d6e3425ab23130c8aa1d4f86:
      title: A Song to Aid the Recollection of Parental Kindness and Encourage the
        Recitation of the Maṇi Mantra
      parent: Songs
    1ed3f6e846e646a79c8a75e4abbeb537:
      title: An Appeal for the Prosperity of Teaching and Studying the Five Major
        Scriptures
      parent: Summoning Prosperity
    91614d4d96464a4aa036f17cb217905f:
      title: 'The Summoning Hook of Wish-Fulfilment: An Appeal for Prosperity'
      parent: Summoning Prosperity
created_at: '2022-03-01T00:31:51.673505'
last_modified_at: '2022-03-01T00:31:51.673511'
